version: 2
sources:
    - name: staging
      description: "Raw data for staging."
      database: zoomcamp-487513
      schema: zoomcamp
      tables:
        - name: yellow_tripdata
        - name: green_tripdata